### ISSUE TITLE
C39a & C39b & C39c & 40a & 40b & 40c

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/utValidateR#62]
A couple things: I saw a class with zero enrollment.  Those should be excluded from this check.  I saw a class where the campus was XXX those should be excluded from this check.

**Comment by andreabr-dixie** [comment]
Looks like these should be looking at specific terms, but they are not.

**Comment by andreabringhurst** [comment]
There are no errors in the courses file, so I'm not sure if this is still an issue.

**Comment by cdemkegit** [comment]
@andreabringhurst I'm going to close this issue we can reopen it if we see errors from USHE.
