### ISSUE TITLE
SC10B isn't working right

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/utValidateR#87]
USHE found errors for Fall EOT
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

sc_inst | sc_banner_id | sc_crs_sbj | sc_crs_num | sc_crs_sec | sc_student_type | sc_earned_cr | sc_grade | c_budget_code | c_end_date | sc_crn
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
3671 | D00203826 | BIOL | 1610 | 88J | CC | 0 |   | SF | 20230525 | 41193
3671 | D00203826 | BIOL | 1615 | 88J | CC | 0 |   | SF | 20230525 | 41194
3671 | D00216758 | BIOL | 1015 | 82J | CC | 0 |   | SF | 20230525 | 43877
3671 | D00216758 | BIOL | 1200 | 82J | CC | 0 |   | SF | 20230525 | 43876
3671 | D00233619 | CHIN | 3116 | 61V | CC | 0 |   | BC | 20230525 | 43609
3671 | D00234122 | CHEM | 1010 | 81J | CC | 0 |   | SF | 20230525 | 41646
3671 | D00234122 | CHEM | 1015 | 81J | CC | 0 |   | SF | 20230525 | 41647
3671 | D00310162 | BIOL | 1015 | 83J | CC | 0 |   | SF | 20230525 | 42940
3671 | D00310162 | BIOL | 1200 | 83J | CC | 0 |   | SF | 20230525 | 42939
3671 | D00397016 | BIOL | 1015 | 83J | CC | 0 |   | SF | 20230525 | 42940

</body>
</html>

**Comment by andreabringhurst** [comment]
Here's some additional information on this issue.
It looks like I made this after USHE had sent a fix file. This was the fix file results. It looks like USHE found errors, when our check did not.
I'm not sure if we are still getting SC10B errors. @JoyBaule have we received any SC10B errors in the last 2-3 fix files for Student Courses?

**Comment by JoyBaule** [comment]
@andreabringhurst  We have had this error but it was due to timing and we provided updates in the USHE Grade Update report submission.

**Comment by cdemkegit** [comment]
@JoyBaule does that mean this issue can be closed without any changes or do we still need to fix an error element in utValidateR? same with the SC10B?

**Comment by JoyBaule** [comment]
@cdemkegit I think you can close it unless you foresee it creating a problem in the future.

**Comment by cdemkegit** [comment]
I'm going to close this issue. If we notice it popping up again we can just reopen this issue.
