### ISSUE TITLE
G04a - Missing County Code

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/utValidateR#92]
Can you make this distinct? I realize that it is pulling for every award issued, but we are not displaying the award information so there are duplicates.

**Comment by andreabringhurst** [comment]
I can't check this since there are currently no errors. But I'm assuming it hasn't been fixed. 
If a student has been awarded two degrees, but is missing the county code, I only want to see the student once (not every degree, because it gets fixed on the student record, not in the graduation record (the table is an admissions table not a graduation table).

**Comment by cdemkegit** [comment]
This may be easier in the App as well? 
@andreabringhurst We want to check all of them just report on Distinct? 
@mkhassan-isu could this be done in the App?

**Comment by andreabringhurst** [comment]
@cdemkegit I talked with @mkhassan-isu about this yesterday. Yes, we want to check all the records and just report on the distinct. The issue is, that every row is a credential (a degree awarded), but this is checking a demographic field. A student could get more than one credential (so they would be listed more than once), but their demographic data is on the student table and exists only once. The person receiving the error, only needs to fix one record not multiple records.

**Comment by MattNickodemus** [comment]
@mkhassan-isu The solution in feature buttons looks like it might not be the best solution. I am confused about why we're including the county code as a data point in the graduation table?

**Comment by andreabringhurst** [comment]
@MattNickodemus and I discussed this issue. We determined that the reason for the app is to display USHE errors. If we deduplicate the errors as I suggested in this issue, although it is easier for the user, it doesn't allow for the alignment with USHE errors which is the main reason for the app. I am going to close this issue and we are not going to pursue it any more.
